CREATE TABLE EMP_DEPT
(DEPT_ID NUMBER(5),DEPT_NAME VARCHAR2(20),DEPT_LOCATION VARCHAR2(20),PRIMARY KEY (DEPT_ID)); 


CREATE TABLE EMP_INFO
(EMP_ID NUMBER(5), EMP_NAME VARCHAR2(20),ADDRESS VARCHAR2(50),CONTACT NUMBER(15),DEPT_ID NUMBER(5), NIC NUMBER(20), 
EMP_HIREDATE VARCHAR2(20),PRIMARY KEY (EMP_ID), FOREIGN KEY (DEPT_ID) REFERENCES EMP_DEPT);


CREATE TABLE EMP_SALARY
(EMP_ID NUMBER(5),EMP_SALERY NUMBER(10),EMP_RANK VARCHAR2(20),JOB_TITLE VARCHAR2(20), PRIMARY KEY (EMP_ID), FOREIGN KEY (EMP_ID) REFERENCES EMP_INFO );


CREATE TABLE EMP_SKILLS
(EMP_ID NUMBER(5),EMP_SKILLS VARCHAR2(20), FOREIGN KEY (EMP_ID) REFERENCES EMP_INFO);


CREATE TABLE CUSTOMERS_1
(C_ID NUMBER(5),CUSTOMER_NAME VARCHAR2(20),
CUSTOMER_CONTACT NUMBER(20),CUSTOMER_ADDRESS VARCHAR2(50),PRIMARY KEY (C_ID));


CREATE TABLE MENU
(ITEM_ID NUMBER(5),ITEM_DESCRIPTION VARCHAR2(15),ITEM_CODE VARCHAR(10),PURCHASE_PRICE NUMBER(10),SOLD_PRICE NUMBER(10),PRIMARY KEY(ITEM_ID));


CREATE TABLE HOME_DELIEVERY
(C_ID NUMBER(5),ORDER_ID NUMBER(5),FOREIGN KEY (C_ID) REFERENCES CUSTOMERS_1);


CREATE TABLE ON_PLACE
(C_ID NUMBER(5),ORDER_NO NUMBER(10), FOREIGN KEY(C_ID) REFERENCES CUSTOMERS_1);


CREATE TABLE ORDERS
(ORDER_NO NUMBER(10), ORDER_DATE VARCHAR2(20), C_ID NUMBER(5),FOREIGN KEY(C_ID) REFERENCES CUSTOMERS_1);

CREATE TABLE ACCOUNTS
(C_ID NUMBER(5),AMOUNT NUMBER(10),HOMEDELIVERY_CHARGES NUMBER(10),DISCOUNT NUMBER(10),TOTAL_AMOUNT NUMBER(10),
FOREIGN KEY(C_ID) REFERENCES CUSTOMERS_1);


CREATE TABLE STOCK
(ITEM_ID NUMBER(5), ITEM_AVALAIBLE VARCHAR2(20),ITEM_SOLD VARCHAR2(20), ITEM_EXPIRED VARCHAR2(20),
PRIMARY KEY(ITEM_ID),FOREIGN KEY(ITEM_ID) REFERENCES MENU);