INSERT INTO EMP_SKILLS
VALUES (01,'Management');

INSERT INTO EMP_SKILLS
VALUES (01,'Computer');

INSERT INTO EMP_SKILLS
VALUES (01,'Conversation');

INSERT INTO EMP_SKILLS
VALUES (01,'Presentation');

INSERT INTO EMP_SKILLS
VALUES (01,'Management');

INSERT INTO EMP_SKILLS
VALUES (01,'Spoken');

INSERT INTO EMP_SKILLS
VALUES (02,'Spokeen');

INSERT INTO EMP_SKILLS
VALUES (02,'Cooking');

INSERT INTO EMP_SKILLS
VALUES (03,'Conversation');

INSERT INTO EMP_SKILLS
VALUES (03,'Computer');

INSERT INTO EMP_SKILLS
VALUES (03,'Spoken');

INSERT INTO EMP_SKILLS
VALUES (04,'Waitering');

INSERT INTO EMP_SKILLS
VALUES (05,'Cooking');

INSERT INTO EMP_SKILLS
VALUES (05,'Waitering');

INSERT INTO EMP_SKILLS
VALUES (06,'Conversation');

INSERT INTO EMP_SKILLS
VALUES (06,'Spoken');

INSERT INTO EMP_SKILLS
VALUES (07,'Computer');

INSERT INTO EMP_SKILLS
VALUES (07,'Presentation');

INSERT INTO EMP_SKILLS
VALUES (07,'Spoken');

INSERT INTO EMP_SKILLS
VALUES (08,'Cooking');

INSERT INTO EMP_SKILLS
VALUES (08,'CONVERSATION');

INSERT INTO EMP_SKILLS
VALUES (08,'Presentation');

INSERT INTO EMP_SKILLS
VALUES (08,'Waitering');